export const CHAINE_VALEUR_LIST_REQUEST = "CHAINE_VALEUR_LIST_REQUEST"
export const CHAINE_VALEUR_LIST_SUCCESS = "CHAINE_VALEUR_LIST_SUCCESS"
export const CHAINE_VALEUR_LIST_FAIL = "CHAINE_VALEUR_LIST_FAIL"
