export const REGION_LIST_REQUEST = "REGION_LIST_REQUEST"
export const REGION_LIST_SUCCESS = "REGION_LIST_SUCCESS"
export const REGION_LIST_FAIL = "REGION_LIST_FAIL"

export const PREFECTURE_LIST_REQUEST = "PREFECTURE_LIST_REQUEST"
export const PREFECTURE_LIST_SUCCESS = "PREFECTURE_LIST_SUCCESS"
export const PREFECTURE_LIST_FAIL = "PREFECTURE_LIST_FAIL"

export const CANTON_LIST_REQUEST = "CANTON_LIST_REQUEST"
export const CANTON_LIST_SUCCESS = "CANTON_LIST_SUCCESS"
export const CANTON_LIST_FAIL = "CANTON_LIST_FAIL"

export const VILLAGE_LIST_REQUEST = "VILLAGE_LIST_REQUEST"
export const VILLAGE_LIST_SUCCESS = "VILLAGE_LIST_SUCCESS"
export const VILLAGE_LIST_FAIL = "VILLAGE_LIST_FAIL"
